### ISSUE TITLE
Stream pipe error

### ISSUE THREAD

**Issue by schurlinga** [s-KaiNet/sp-request#7]
Hello,

I tried using sp-request to upload files from a webserver to sharepoint via stream.

Code:

    var request = require("request-promise");
    
    spr.requestDigest(spWebUrl)
        .then(function (digest) {
            globalRequestOptions.headers["X-RequestDigest"] = digest;
            globalRequestOptions.url = spWebUrl + '/_api/web/GetFolderByServerRelativeUrl(\'' + folder + '\')/files/add(url=\'file.pdf\', overwrite=true)';
            globalRequestOptions.method = "POST";
            return request
                .get('http://webserver/Original%20file/917749.pdf')
                .pipe(spr(globalRequestOptions)); // throws error
                // .pipe(request(globalRequestOptions)); // no error
        });

With sp-request i get following error:

    TypeError: dest.on is not a function
        at Request.Stream.pipe (stream.js:45:8)
        at Request.pipe (path\node_modules\request\request.js:1502:34)
        at path\server.js:72:30
        at tryCatcher (path\node_modules\bluebird\js\release\util.js:16:23)
        at Promise.module.exports.Promise._settlePromiseFromHandler (path\node_modules\bluebird\js\release\promise.js:512:31)
        at Promise.module.exports.Promise._settlePromise (path\node_modules\bluebird\js\release\promise.js:569:18)
        at Promise.module.exports.Promise._settlePromise0 (path\node_modules\bluebird\js\release\promise.js:614:10)
        at Promise.module.exports.Promise._settlePromises (path\node_modules\bluebird\js\release\promise.js:693:18)
        at Async._drainQueue (path\node_modules\bluebird\js\release\async.js:133:16)
        at Async._drainQueues (path\node_modules\bluebird\js\release\async.js:143:10)
        at Immediate.e.Async.drainQueues (path\node_modules\bluebird\js\release\async.js:17:14)
        at runCallback (timers.js:649:20)
        at tryOnImmediate (timers.js:622:5)
        at processImmediate [as _immediateCallback] (timers.js:594:5)

**Comment by s-KaiNet** [comment]
Will take a look in the nearest time

**Comment by s-KaiNet** [comment]
So I can say that `sp-request` doesn't support streaming. It overrides some `request` defaults and always respond with `IncomingMessage` thus stream option is not working.
